.TH BETA 1 2018 "Alexander Shpilkin"
.SH NAME 
beta \- sample binomial distributions
.SH SYNOPSIS
\fBbeta \fIcount
.SH DESCRIPTION
Given a population size \fIN\fR and a sample \fIn\fR from a binomial
distribution with parameters (\fIN\fR, \fIp\fR), \fIbeta\fR computes
\fIcount\fR more samples from it, assuming a uniform Bayesian prior for the
unknown parameter \fIp\fR.
.PP
The values of \fIN\fR and \fIn\fR are read from standard input, in this order,
separated by whitespace. Several distributions can be specified, one per line.
For each distribution, \fIcount\fR lines are written, containing the population
size \fIN\fR and the sampled value. Values on output are separated by a single
tab character.
.SH LIMITATIONS
The population size \fIN\fR is limited to about 30000, which is also the range
of values for which \fIbeta\fR can be expected to produce reasonably accurate
results with acceptable speed.
.SH AUTHOR
Alexander Shpilkin <ashpilkin@gmail.com>
.SH SEE ALSO
.IR hist (1),
.IR cut (1),
.IR awk (1)
